import { Lato } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import SideMenu from "./_components/SideMenu";

const lato = Lato({ 
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], 
});

export const metadata = {
  title: "Css test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className={styles.main}>
          <SideMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
